spring:
  jpa:
    # 전송 쿼리 확인
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    # 테이블 생성 후에 data.sql 실행
    defer-datasource-initialization: true

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa

  h2:
    console:
      enabled: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: <<839046824216-95g4h0vkpneva58a2gbuo7hgrmogrmah.apps.googleusercontent.com>>
            client-secret: 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

jwt:
  issuer: ajufresh@gmail.com
  secret_key: study-springboot
